[package]
name = "echo_server"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
build_info = { path = "../../lib/build_info" }

clap = { version = "4.2.7", features = ["derive"] }
const_format = "0.2.30"
figment = { version = "0.10.8", features = ["json", "test"] }
itertools = "0.10.5"
rocket = "0.5.0-rc.3"
