name: Docker CI

on:
  push:
    branches:
      - main

env:
  DOCKER_APP_PORT: "12365"
  LOCAL_REGISTRY_PORT: "5000"

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      matrix:
        include:
          - app-name: go-echo-server
            docker-file: docker/go_echo_server/Dockerfile
            port: "80"
            health-check-path: /headers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.docker-file }}
          context: .
          push: true
          tags: localhost:${{ env.LOCAL_REGISTRY_PORT }}/${{ matrix.app-name }}:latest

      - name: Inspect with Docker Buildx
        shell: bash
        run: |
          docker buildx imagetools inspect localhost:${{ env.LOCAL_REGISTRY_PORT }}/${{ matrix.app-name }}:latest

      - name: Test with docker run
        run: |
          container_id=$(docker run -d -p ${{ env.DOCKER_APP_PORT }}:${{ matrix.port }} --rm localhost:${{ env.LOCAL_REGISTRY_PORT }}/${{ matrix.app-name }}:latest)
          sleep 5
          curl -v localhost:${{ env.DOCKER_APP_PORT }}${{ matrix.health-check-path }}
          docker stop $container_id
