name: Docker CI

on:
  push:
    branches:
      - main

env:
  LOCAL_REGISTRY_PORT: "5000"

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      matrix:
        include:
          - docker-file: docker/go_echo_server/Dockerfile
            app-name: go-echo-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.docker-file }}
          context: .
          push: true
          tags: localhost:5000/name/app:latest

      - name: Inspect
        shell: bash
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest
