name: Go CI

on:
  push:
    branches:
    - main

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
        - go/cmd/simple

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: ${{ matrix.module }}
      shell: bash
      run: |
        go build -v -mod readonly ./...

    - name: Run tests
      working-directory: ${{ matrix.module }}
      shell: bash
      run: |
        go test -v -mod readonly ./...

    - name: Run tests  with race detector
      working-directory: ${{ matrix.module }}
      shell: bash
      run: |
        go test -v -mod readonly -race ./...
