name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - go

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Check codestyle
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          gofmt -l -d .

      - name: Build
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go build -v -mod readonly ./...

      - name: Run tests
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod readonly ./...

      - name: Run tests with race detector
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod readonly -race ./...
